name: CD

on:
  push:
    branches: [ master, next ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        python3 -m pip install --upgrade build
        python3 -m build
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
        additional_options: --prerelease --verbosity DEBUG
        directory: dist