name: CD

on:
  push:
    branches: [ master, next ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        python3 -m pip install --upgrade build
        python3 -m build
        ls
        ls dist
    - name: Publish on PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        verbose: true
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        packages-dir: "dist"